/** Spec §5.1 — Signal: a strategy's proposed entry, before any aggregation. */

import type { Direction } from "./bar.js";

export interface Signal {
  /** UUID generated by the strategy. */
  id: string;
  originatingStrategy: string;
  instrument: string;
  direction: Direction;
  proposedEntryPrice: number;
  proposedStopPrice: number;
  proposedTargetPrice: number;
  /** Fraction of the strategy's allocation to deploy on this signal, 0..1. */
  proposedSizeFractionOfAllocation: number;
  /** Higher = more urgent. Used by the orchestrator for tie-breaking. */
  urgencyScore: number;
  /** Strategy-specific tag (e.g. "asian_sweep_long"). */
  signalType: string;
  /** Human-readable reason for audit logs. */
  entryReason: string;
  /** Timestamp of the bar that generated this signal. */
  generatedAtBar: Date;
  metadata: Record<string, unknown>;
}
